RULES = {
    1: ("xmldokument", ["xmldecl", "element"]),
    2: ("xmldokument", ["element"]),
    3: ("xmldecl", ["<?xml", "version=", "vernumb", "?>"]),
    4: ("vernumb", ["number", ".", "number"]),
    5: ("element", ["<", "name", "element_tail"]),
    6: ("element_tail", ["/>"]),
    7: ("element_tail", [">", "element_content", "endtag"]),
    8: ("element_content", ["word"]),
    9: ("element_content", ["element"]),
    10: ("element_content", []),
    11: ("endtag", ["</", "name", ">"]),
    12: ("name", ["namestart", "name_tail"]),
    13: ("namestart", ["letter"]),
    14: ("namestart", ["_"]),
    15: ("namestart", [":"]),
    16: ("name_tail", ["namechar", "name_tail"]),
    17: ("name_tail", []),
    18: ("namechar", ["letter"]),
    19: ("namechar", ["digit"]),
    20: ("namechar", ["."]),
    21: ("namechar", ["-"]),
    22: ("namechar", ["_"]),
    23: ("namechar", [":"]),
    24: ("letter", ["LETTER"]),
    25: ("number", ["digit", "number_tail"]),
    26: ("number_tail", ["number"]),
    27: ("number_tail", []),
    28: ("digit", ["NUMBER"]),
    29: ("word", ["char", "word_tail"]),
    30: ("word_tail", ["word"]),
    31: ("word_tail", []),
    32: ("char", ["letter"]),
    33: ("char", ["digit"]),
    34: ("char", ["."]),
    35: ("char", ["-"]),
    36: ("char", ["_"]),
    37: ("char", [":"]),
    38: ("char", ["!"]),
    39: ("char", ["@"]),
    40: ("char", ["#"]),
}
